parameters:
  - name: 'ENV'
    displayName: 'Environment to deploy'
    type: string
  - name: 'DEFINITION_NAME'
    displayName: 'Definition name to be deployed'
    type: string
  - name: 'WORKING_DIR_MODULE'
    displayName: 'module working dir'
    type: string
    default: ''
  - name: 'ENV_FOLDER'
    displayName: 'Environment folder location'
    type: string
  - name: 'SC_PLAN_NAME'
    type: string
  - name: 'SC_APPLY_NAME'
    type: string
  - name: 'AKS_APISERVER_URL'
    type: string
    default: ''
  - name: 'AKS_AZURE_DEVOPS_SA_CACRT'
    type: string
    default: ''
  - name: 'AKS_AZURE_DEVOPS_SA_TOKEN'
    type: string
    default: ''
  - name: 'AKS_NAME'
    type: string
    default: ''
  - name: 'SECOND_AKS_APISERVER_URL'
    type: string
    default: ''
  - name: 'SECOND_AKS_AZURE_DEVOPS_SA_CACRT'
    type: string
    default: ''
  - name: 'SECOND_AKS_AZURE_DEVOPS_SA_TOKEN'
    type: string
    default: ''
  - name: 'SECOND_AKS_NAME'
    type: string
    default: ''
  - name: 'POOL_NAME'
    type: string
    default: ''
  - name: 'TIME_OUT'
    type: number
    default: 15
  - name: 'MODULE_USE_AKS'
    type: boolean
    default: false
  - name: 'MODULE_USE_SECOND_AKS'
    type: string # using string because parameter value comes from pipeline definition and is not interpreted as boolean
    default: 'false'
  - name: 'USE_SOPS'
    type: boolean
    default: false

stages:
  - ${{ if ne(parameters.WORKING_DIR_MODULE, '') }}:
    #MODULE
    - template: templates/terraform-plan-apply/template.yaml@terraform
      parameters:
        FULL_DOMAIN_NAME: "${{parameters.DEFINITION_NAME}}_module"
        TF_ENVIRONMENT_FOLDER: "${{parameters.ENV_FOLDER}}"
        ENVIRONMENT: "${{parameters.ENV}}"
        AZURE_DEVOPS_POOL_AGENT_NAME: "${{parameters.POOL_NAME}}"
        WORKINGDIR: ${{ parameters.WORKING_DIR_MODULE }}
        AZURE_SERVICE_CONNECTION_PLAN_NAME: "${{parameters.SC_PLAN_NAME}}"
        AZURE_SERVICE_CONNECTION_APPLY_NAME: "${{parameters.SC_APPLY_NAME}}"
        USE_SOPS: ${{ parameters.USE_SOPS }}
        ${{ if eq(parameters.MODULE_USE_AKS, 'true') }}:
          AKS_NAME: ${{ parameters.AKS_NAME }}
          AKS_API_SERVER_URL: ${{ parameters.AKS_APISERVER_URL }}
          AKS_AZURE_DEVOPS_SA_CA_CRT: ${{ parameters.AKS_AZURE_DEVOPS_SA_CACRT }}
          AKS_AZURE_DEVOPS_SA_TOKEN: ${{ parameters.AKS_AZURE_DEVOPS_SA_TOKEN }}
        ${{ if ne(parameters.MODULE_USE_SECOND_AKS, 'false') }}:
          SECOND_AKS_NAME: ${{ parameters.SECOND_AKS_NAME }}
          SECOND_AKS_API_SERVER_URL: ${{ parameters.SECOND_AKS_APISERVER_URL }}
          SECOND_AKS_AZURE_DEVOPS_SA_CA_CRT: ${{ parameters.SECOND_AKS_AZURE_DEVOPS_SA_CACRT }}
          SECOND_AKS_AZURE_DEVOPS_SA_TOKEN: ${{ parameters.SECOND_AKS_AZURE_DEVOPS_SA_TOKEN }}
