pr:
  autoCancel: true
  branches:
    include:
      - main
  paths:
    include:
      - 'src/06_elastic__resources_deployment'
    exclude:
      - '**/*.lock.hcl'
      - '**/*.md'

parameters:
  - name: 'STAG'
    displayName: 'Run on STAGING environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Run on PROD environment'
    type: boolean
    default: True
    values:
      - False
      - True


pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/heads/support-two-clusters
      endpoint: "azure-devops-github-ro"

variables:
  TIME_OUT: 30
  # working dir
  WORKING_DIR: 'src/06_elastic__resources_deployment'

stages:
    #STAGING
  - ${{ if eq(parameters['STAG'], true) }}:
    - template: './base-code-review-pipelines.yml'
      parameters:
        ENV: "uat"
        ENV_FOLDER: "$(TF_TARGET)-stag"
        WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_UAT)'
        TIME_OUT: ${{ variables.TIME_OUT }}
        TF_SUMMARIZE: true

  #PROD
  - ${{ if eq(parameters['PROD'], true) }}:
    - template: './base-code-review-pipelines.yml'
      parameters:
        ENV: "prod"
        ENV_FOLDER: "$(TF_TARGET)-prod"
        WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_PROD)'
        TIME_OUT: ${{ variables.TIME_OUT }}
        TF_SUMMARIZE: true