pr:
  autoCancel: true
  branches:
    include:
      - main
  paths:
    include:
      - 'src/04_elastic_deployment'
    exclude:
      - '**/*.lock.hcl'
      - '**/*.md'

parameters:
  - name: 'STAG'
    displayName: 'Run on STAGING environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Run on PROD environment'
    type: boolean
    default: True
    values:
      - False
      - True

  - name: 'ARC_P4PA'
    displayName: 'Run for ARC and P4PA environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PAGOPA'
    displayName: 'Run on PAGOPA environment'
    type: boolean
    default: True
    values:
      - False
      - True



pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v5.2.1
      endpoint: "azure-devops-github-ro"

variables:
  TIME_OUT: 30
  # working dir
  WORKING_DIR: 'src/04_elastic_deployment'

stages:
    #STAGING
  - ${{ if eq(parameters['STAG'], true) }}:
      - ${{ if eq(parameters['ARC_P4PA'], true) }}:
        - template: './base-code-review-pipelines.yml'
          parameters:
            ENV: "arp4pa-stag"
            ENV_FOLDER: "arp4pa-stag"
            WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
            SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_UAT)'
            POOL_NAME: '$(TF_POOL_NAME_UAT)'
            TIME_OUT: ${{ variables.TIME_OUT }}
            TF_SUMMARIZE: true
      - ${{ if eq(parameters['PAGOPA'], true) }}:
          - template: './base-code-review-pipelines.yml'
            parameters:
              ENV: "pagopa-stag"
              ENV_FOLDER: "pagopa-stag"
              WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
              SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_UAT)'
              POOL_NAME: '$(TF_POOL_NAME_UAT)'
              TIME_OUT: ${{ variables.TIME_OUT }}
              TF_SUMMARIZE: true

  #PROD
  - ${{ if eq(parameters['PROD'], true) }}:
      - ${{ if eq(parameters['ARC_P4PA'], true) }}:
          - template: './base-code-review-pipelines.yml'
            parameters:
              ENV: "arp4pa-prod"
              ENV_FOLDER: "arp4pa-prod"
              WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
              SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_PROD)'
              POOL_NAME: '$(TF_POOL_NAME_PROD)'
              TIME_OUT: ${{ variables.TIME_OUT }}
              TF_SUMMARIZE: true
      - ${{ if eq(parameters['PAGOPA'], true) }}:
          - template: './base-code-review-pipelines.yml'
            parameters:
              ENV: "pagopa-prod"
              ENV_FOLDER: "pagopa-prod"
              WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
              SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_PROD)'
              POOL_NAME: '$(TF_POOL_NAME_PROD)'
              TIME_OUT: ${{ variables.TIME_OUT }}
              TF_SUMMARIZE: true