pr:
  autoCancel: true
  branches:
    include:
      - main
  paths:
    include:
      - 'src/07_elastic_resources_app'
    exclude:
      - '**/*.lock.hcl'
      - '**/*.md'

parameters:
  - name: 'DEV'
    displayName: 'Run on DEV environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'UAT'
    displayName: 'Run on UAT environment'
    type: boolean
    default: True
    values:
      - False
      - True
  - name: 'PROD'
    displayName: 'Run on PROD environment'
    type: boolean
    default: True
    values:
      - False
      - True





pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v6.12.0
      endpoint: "azure-devops-github-ro"

variables:
  TIME_OUT: 30
  # working dir
  WORKING_DIR: 'src/07_elastic_resources_app'

stages:
    #DEV
  - ${{ if eq(parameters['DEV'], true) }}:
    - template: './base-code-review-pipelines.yml'
      parameters:
        ENV: "dev"
        ENV_FOLDER: "$(TF_TARGET)-dev"
        WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_DEV)'
        TIME_OUT: ${{ variables.TIME_OUT }}
        TF_SUMMARIZE: true

  #UAT
  - ${{ if eq(parameters['UAT'], true) }}:
    - template: './base-code-review-pipelines.yml'
      parameters:
        ENV: "uat"
        ENV_FOLDER: "$(TF_TARGET)-uat"
        WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_UAT)'
        TIME_OUT: ${{ variables.TIME_OUT }}
        TF_SUMMARIZE: true


  #PROD
  - ${{ if eq(parameters['PROD'], true) }}:
    - template: './base-code-review-pipelines.yml'
      parameters:
        ENV: "prod"
        ENV_FOLDER: "$(TF_TARGET)-prod"
        WORKING_DIR_MODULE: ${{ variables.WORKING_DIR }}
        SC_PLAN_NAME: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_PROD)'
        TIME_OUT: ${{ variables.TIME_OUT }}
        TF_SUMMARIZE: true